# Etapa 1 (stage 1): Compilação do projeto com Node
FROM node:18-alpine AS builder

# Pasta padrão
WORKDIR /usr/app/temp

# Copiar arquivos do projeto e compilar para gerar o arquivo JAR
COPY . .

# Instalar dependências e compilar o projeto para gerar o arquivo JAR
RUN yarn install

# Compilar o projeto
RUN yarn build



# Etapa 2 (stage 2): Execução do projeto Nginx
FROM nginx:1.25-alpine as production

# Configuracao do Nginx
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

## Remover arquivos padrão do Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copiar o arquivos da aplicação Frontend da etapa 1
COPY --from=builder /usr/app/temp/build /usr/share/nginx/html


# Porta padrão
EXPOSE 3000

# Execução da aplicação
ENTRYPOINT ["nginx", "-g", "daemon off;"]